-----------------------------------
-- Abjurations
-- Used by Alphollon C Meriard
-----------------------------------
xi = xi or {}

invaderXim.abjurations =
{
    -- (5 IDs/lines per transaction)
    --  abjuration,
    --  item,
    --  item -1,
    --  nq reward,
    --  hq reward

    -- Begin Sky Abjurations
    invaderXim.item.LIBATION_ABJURATION,
    invaderXim.item.BOTTLE_OF_CURSED_BEVERAGE,
    invaderXim.item.BOTTLE_OF_CURSED_BEVERAGE,
    invaderXim.item.BOTTLE_OF_AMRITA,
    invaderXim.item.BOTTLE_OF_AMRITA,

    invaderXim.item.OBLATION_ABJURATION,
    invaderXim.item.BOWL_OF_CURSED_SOUP,
    invaderXim.item.BOWL_OF_CURSED_SOUP,
    invaderXim.item.BOWL_OF_AMBROSIA,
    invaderXim.item.BOWL_OF_AMBROSIA,

    invaderXim.item.DRYADIC_ABJURATION_HEAD,
    invaderXim.item.CURSED_KABUTO,
    invaderXim.item.CURSED_KABUTO_M1,
    invaderXim.item.SHURA_ZUNARI_KABUTO,
    invaderXim.item.SHURA_ZUNARI_KABUTO_P1,

    invaderXim.item.DRYADIC_ABJURATION_BODY,
    invaderXim.item.CURSED_TOGI,
    invaderXim.item.CURSED_TOGI_M1,
    invaderXim.item.SHURA_TOGI,
    invaderXim.item.SHURA_TOGI_P1,

    invaderXim.item.DRYADIC_ABJURATION_HANDS,
    invaderXim.item.CURSED_KOTE,
    invaderXim.item.CURSED_KOTE_M1,
    invaderXim.item.SHURA_KOTE,
    invaderXim.item.SHURA_KOTE_P1,

    invaderXim.item.DRYADIC_ABJURATION_LEGS,
    invaderXim.item.CURSED_HAIDATE,
    invaderXim.item.CURSED_HAIDATE_M1,
    invaderXim.item.SHURA_HAIDATE,
    invaderXim.item.SHURA_HAIDATE_P1,

    invaderXim.item.DRYADIC_ABJURATION_FEET,
    invaderXim.item.CURSED_SUNE_ATE,
    invaderXim.item.CURSED_SUNE_ATE_M1,
    invaderXim.item.SHURA_SUNE_ATE,
    invaderXim.item.SHURA_SUNE_ATE_P1,

    invaderXim.item.EARTHEN_ABJURATION_HEAD,
    invaderXim.item.CURSED_CELATA,
    invaderXim.item.CURSED_CELATA_M1,
    invaderXim.item.ADAMAN_CELATA,
    invaderXim.item.ARMADA_CELATA,

    invaderXim.item.EARTHEN_ABJURATION_BODY,
    invaderXim.item.CURSED_HAUBERK,
    invaderXim.item.CURSED_HAUBERK_M1,
    invaderXim.item.ADAMAN_HAUBERK,
    invaderXim.item.ARMADA_HAUBERK,

    invaderXim.item.EARTHEN_ABJURATION_HANDS,
    invaderXim.item.CURSED_MUFFLERS,
    invaderXim.item.CURSED_MUFFLERS_M1,
    invaderXim.item.ADAMAN_MUFFLERS,
    invaderXim.item.ARMADA_MUFFLERS,

    invaderXim.item.EARTHEN_ABJURATION_LEGS,
    invaderXim.item.CURSED_BREECHES,
    invaderXim.item.CURSED_BREECHES_M1,
    invaderXim.item.ADAMAN_BREECHES,
    invaderXim.item.ARMADA_BREECHES,

    invaderXim.item.EARTHEN_ABJURATION_FEET,
    invaderXim.item.CURSED_SOLLERETS,
    invaderXim.item.CURSED_SOLLERETS_M1,
    invaderXim.item.ADAMAN_SOLLERETS,
    invaderXim.item.ARMADA_SOLLERETS,

    invaderXim.item.AQUARIAN_ABJURATION_HEAD,
    invaderXim.item.CURSED_CROWN,
    invaderXim.item.CURSED_CROWN_M1,
    invaderXim.item.ZENITH_CROWN,
    invaderXim.item.ZENITH_CROWN_P1,

    invaderXim.item.AQUARIAN_ABJURATION_BODY,
    invaderXim.item.CURSED_DALMATICA,
    invaderXim.item.CURSED_DALMATICA_M1,
    invaderXim.item.DALMATICA,
    invaderXim.item.DALMATICA_P1,

    invaderXim.item.AQUARIAN_ABJURATION_HANDS,
    invaderXim.item.CURSED_MITTS,
    invaderXim.item.CURSED_MITTS_M1,
    invaderXim.item.ZENITH_MITTS,
    invaderXim.item.ZENITH_MITTS_P1,

    invaderXim.item.AQUARIAN_ABJURATION_LEGS,
    invaderXim.item.CURSED_SLACKS,
    invaderXim.item.CURSED_SLACKS_M1,
    invaderXim.item.ZENITH_SLACKS,
    invaderXim.item.ZENITH_SLACKS_P1,

    invaderXim.item.AQUARIAN_ABJURATION_FEET,
    invaderXim.item.CURSED_PUMPS,
    invaderXim.item.CURSED_PUMPS_M1,
    invaderXim.item.ZENITH_PUMPS,
    invaderXim.item.ZENITH_PUMPS_P1,

    invaderXim.item.MARTIAL_ABJURATION_HEAD,
    invaderXim.item.CURSED_SCHALLER,
    invaderXim.item.CURSED_SCHALLER_M1,
    invaderXim.item.KOENIG_SCHALLER,
    invaderXim.item.KAISER_SCHALLER,

    invaderXim.item.MARTIAL_ABJURATION_BODY,
    invaderXim.item.CURSED_CUIRASS,
    invaderXim.item.CURSED_CUIRASS_M1,
    invaderXim.item.KOENIG_CUIRASS,
    invaderXim.item.KAISER_CUIRASS,

    invaderXim.item.MARTIAL_ABJURATION_HANDS,
    invaderXim.item.CURSED_HANDSCHUHS,
    invaderXim.item.CURSED_HANDSCHUHS_M1,
    invaderXim.item.KOENIG_HANDSCHUHS,
    invaderXim.item.KAISER_HANDSCHUHS,

    invaderXim.item.MARTIAL_ABJURATION_LEGS,
    invaderXim.item.CURSED_DIECHLINGS,
    invaderXim.item.CURSED_DIECHLINGS_M1,
    invaderXim.item.KOENIG_DIECHLINGS,
    invaderXim.item.KAISER_DIECHLINGS,

    invaderXim.item.MARTIAL_ABJURATION_FEET,
    invaderXim.item.CURSED_SCHUHS,
    invaderXim.item.CURSED_SCHUHS_M1,
    invaderXim.item.KOENIG_SCHUHS,
    invaderXim.item.KAISER_SCHUHS,

    invaderXim.item.WYRMAL_ABJURATION_HEAD,
    invaderXim.item.CURSED_MASK,
    invaderXim.item.CURSED_MASK_M1,
    invaderXim.item.CRIMSON_MASK,
    invaderXim.item.BLOOD_MASK,

    invaderXim.item.WYRMAL_ABJURATION_BODY,
    invaderXim.item.CURSED_MAIL,
    invaderXim.item.CURSED_MAIL_M1,
    invaderXim.item.CRIMSON_SCALE_MAIL,
    invaderXim.item.BLOOD_SCALE_MAIL,

    invaderXim.item.WYRMAL_ABJURATION_HANDS,
    invaderXim.item.CURSED_FINGER_GAUNTLETS,
    invaderXim.item.CURSED_FINGER_GAUNTLETS_M1,
    invaderXim.item.CRIMSON_FINGER_GAUNTLETS,
    invaderXim.item.BLOOD_FINGER_GAUNTLETS,

    invaderXim.item.WYRMAL_ABJURATION_LEGS,
    invaderXim.item.CURSED_CUISSES,
    invaderXim.item.CURSED_CUISSES_M1,
    invaderXim.item.CRIMSON_CUISSES,
    invaderXim.item.BLOOD_CUISSES,

    invaderXim.item.WYRMAL_ABJURATION_FEET,
    invaderXim.item.CURSED_GREAVES,
    invaderXim.item.CURSED_GREAVES_M1,
    invaderXim.item.CRIMSON_GREAVES,
    invaderXim.item.BLOOD_GREAVES,

    invaderXim.item.NEPTUNAL_ABJURATION_HEAD,
    invaderXim.item.CURSED_CAP,
    invaderXim.item.CURSED_CAP_M1,
    invaderXim.item.HECATOMB_CAP,
    invaderXim.item.HECATOMB_CAP_P1,

    invaderXim.item.NEPTUNAL_ABJURATION_BODY,
    invaderXim.item.CURSED_HARNESS,
    invaderXim.item.CURSED_HARNESS_M1,
    invaderXim.item.HECATOMB_HARNESS,
    invaderXim.item.HECATOMB_HARNESS_P1,

    invaderXim.item.NEPTUNAL_ABJURATION_HANDS,
    invaderXim.item.CURSED_GLOVES,
    invaderXim.item.CURSED_GLOVES_M1,
    invaderXim.item.HECATOMB_MITTENS,
    invaderXim.item.HECATOMB_MITTENS_P1,

    invaderXim.item.NEPTUNAL_ABJURATION_LEGS,
    invaderXim.item.CURSED_SUBLIGAR,
    invaderXim.item.CURSED_SUBLIGAR_M1,
    invaderXim.item.HECATOMB_SUBLIGAR,
    invaderXim.item.HECATOMB_SUBLIGAR_P1,

    invaderXim.item.NEPTUNAL_ABJURATION_FEET,
    invaderXim.item.CURSED_LEGGINGS,
    invaderXim.item.CURSED_LEGGINGS_M1,
    invaderXim.item.HECATOMB_LEGGINGS,
    invaderXim.item.HECATOMB_LEGGINGS_P1,

    -- Begin Einherjar Abjurations
    invaderXim.item.PHANTASMAL_ABJURATION_HEAD,
    invaderXim.item.CURSED_HELM,
    invaderXim.item.CURSED_HELM_M1,
    invaderXim.item.SHADOW_HELM,
    invaderXim.item.VALKYRIES_HELM,

    invaderXim.item.PHANTASMAL_ABJURATION_BODY,
    invaderXim.item.CURSED_BREASTPLATE,
    invaderXim.item.CURSED_BREASTPLATE_M1,
    invaderXim.item.SHADOW_BREASTPLATE,
    invaderXim.item.VALKYRIES_BREASTPLATE,

    invaderXim.item.PHANTASMAL_ABJURATION_HANDS,
    invaderXim.item.CURSED_GAUNTLETS,
    invaderXim.item.CURSED_GAUNTLETS_M1,
    invaderXim.item.SHADOW_GAUNTLETS,
    invaderXim.item.VALKYRIES_GAUNTLETS,

    invaderXim.item.PHANTASMAL_ABJURATION_LEGS,
    invaderXim.item.CURSED_CUISHES,
    invaderXim.item.CURSED_CUISHES_M1,
    invaderXim.item.SHADOW_CUISHES,
    invaderXim.item.VALKYRIES_CUISHES,

    invaderXim.item.PHANTASMAL_ABJURATION_FEET,
    invaderXim.item.CURSED_SABATONS,
    invaderXim.item.CURSED_SABATONS_M1,
    invaderXim.item.SHADOW_SABATONS,
    invaderXim.item.VALKYRIES_SABATONS,

    invaderXim.item.HADEAN_ABJURATION_HEAD,
    invaderXim.item.CURSED_HAT,
    invaderXim.item.CURSED_HAT_M1,
    invaderXim.item.SHADOW_HAT,
    invaderXim.item.VALKYRIES_HAT,

    invaderXim.item.HADEAN_ABJURATION_BODY,
    invaderXim.item.CURSED_COAT,
    invaderXim.item.CURSED_COAT_M1,
    invaderXim.item.SHADOW_COAT,
    invaderXim.item.VALKYRIES_COAT,

    invaderXim.item.HADEAN_ABJURATION_HANDS,
    invaderXim.item.CURSED_CUFFS,
    invaderXim.item.CURSED_CUFFS_M1,
    invaderXim.item.SHADOW_CUFFS,
    invaderXim.item.VALKYRIES_CUFFS,

    invaderXim.item.HADEAN_ABJURATION_LEGS,
    invaderXim.item.CURSED_TREWS,
    invaderXim.item.CURSED_TREWS_M1,
    invaderXim.item.SHADOW_TREWS,
    invaderXim.item.VALKYRIES_TREWS,

    invaderXim.item.HADEAN_ABJURATION_FEET,
    invaderXim.item.CURSED_CLOGS,
    invaderXim.item.CURSED_CLOGS_M1,
    invaderXim.item.SHADOW_CLOGS,
    invaderXim.item.VALKYRIES_CLOGS,

    -- Begin Voidwatch/Legion Abjurations
    invaderXim.item.CORVINE_ABJURATION_HEAD,
    invaderXim.item.HEXED_CORONET,
    invaderXim.item.HEXED_CORONET_M1,
    invaderXim.item.HRAFN_CORONET,
    invaderXim.item.HUGINN_CORONET,

    invaderXim.item.CORVINE_ABJURATION_BODY,
    invaderXim.item.HEXED_HAUBERT,
    invaderXim.item.HEXED_HAUBERT_M1,
    invaderXim.item.HRAFN_HAUBERT,
    invaderXim.item.HUGINN_HAUBERT,

    invaderXim.item.CORVINE_ABJURATION_HANDS,
    invaderXim.item.HEXED_GAUNTLETS,
    invaderXim.item.HEXED_GAUNTLETS_M1,
    invaderXim.item.HRAFN_GAUNTLETS,
    invaderXim.item.HUGINN_GAUNTLETS,

    invaderXim.item.CORVINE_ABJURATION_LEGS,
    invaderXim.item.HEXED_HOSE,
    invaderXim.item.HEXED_HOSE_M1,
    invaderXim.item.HRAFN_HOSE,
    invaderXim.item.HUGINN_HOSE,

    invaderXim.item.CORVINE_ABJURATION_FEET,
    invaderXim.item.HEXED_GAMBIERAS,
    invaderXim.item.HEXED_GAMBIERAS_M1,
    invaderXim.item.HRAFN_GAMBIERAS,
    invaderXim.item.HUGINN_GAMBIERAS,

    invaderXim.item.FOREBODING_ABJURATION_HEAD,
    invaderXim.item.HEXED_COIF,
    invaderXim.item.HEXED_COIF_M1,
    invaderXim.item.AUSPEX_COIF,
    invaderXim.item.SPURRINA_COIF,

    invaderXim.item.FOREBODING_ABJURATION_BODY,
    invaderXim.item.HEXED_DOUBLET,
    invaderXim.item.HEXED_DOUBLET_M1,
    invaderXim.item.AUSPEX_DOUBLET,
    invaderXim.item.SPURRINA_DOUBLET,

    invaderXim.item.FOREBODING_ABJURATION_HANDS,
    invaderXim.item.HEXED_GAGES,
    invaderXim.item.HEXED_GAGES_M1,
    invaderXim.item.AUSPEX_GAGES,
    invaderXim.item.SPURRINA_GAGES,

    invaderXim.item.FOREBODING_ABJURATION_LEGS,
    invaderXim.item.HEXED_SLOPS,
    invaderXim.item.HEXED_SLOPS_M1,
    invaderXim.item.AUSPEX_SLOPS,
    invaderXim.item.SPURRINA_SLOPS,

    invaderXim.item.FOREBODING_ABJURATION_FEET,
    invaderXim.item.HEXED_NAILS,
    invaderXim.item.HEXED_NAILS_M1,
    invaderXim.item.AUSPEX_NAILS,
    invaderXim.item.SPURRINA_NAILS,

    invaderXim.item.LENITIVE_ABJURATION_HEAD,
    invaderXim.item.HEXED_MITRA,
    invaderXim.item.HEXED_MITRA_M1,
    invaderXim.item.PAEAN_MITRA,
    invaderXim.item.IASO_MITRA,

    invaderXim.item.LENITIVE_ABJURATION_BODY,
    invaderXim.item.HEXED_BLIAUT,
    invaderXim.item.HEXED_BLIAUT_M1,
    invaderXim.item.PAEAN_BLIAUT,
    invaderXim.item.IASO_BLIAUT,

    invaderXim.item.LENITIVE_ABJURATION_HANDS,
    invaderXim.item.HEXED_CUFFS,
    invaderXim.item.HEXED_CUFFS_M1,
    invaderXim.item.PAEAN_CUFFS,
    invaderXim.item.IASO_CUFFS,

    invaderXim.item.LENITIVE_ABJURATION_LEGS,
    invaderXim.item.HEXED_TIGHTS,
    invaderXim.item.HEXED_TIGHTS_M1,
    invaderXim.item.PAEAN_TIGHTS,
    invaderXim.item.IASO_TIGHTS,

    invaderXim.item.LENITIVE_ABJURATION_FEET,
    invaderXim.item.HEXED_BOOTS,
    invaderXim.item.HEXED_BOOTS_M1,
    invaderXim.item.PAEAN_BOOTS,
    invaderXim.item.IASO_BOOTS,

    invaderXim.item.SUPERNAL_ABJURATION_HEAD,
    invaderXim.item.HEXED_SOMEN,
    invaderXim.item.HEXED_SOMEN_M1,
    invaderXim.item.TENRYU_SOMEN,
    invaderXim.item.TENRYU_SOMEN_P1,

    invaderXim.item.SUPERNAL_ABJURATION_BODY,
    invaderXim.item.HEXED_DOMARU,
    invaderXim.item.HEXED_DOMARU_M1,
    invaderXim.item.TENRYU_DOMARU,
    invaderXim.item.TENRYU_DOMARU_P1,

    invaderXim.item.SUPERNAL_ABJURATION_HANDS,
    invaderXim.item.HEXED_TEKKO,
    invaderXim.item.HEXED_TEKKO_M1,
    invaderXim.item.TENRYU_TEKKO,
    invaderXim.item.TENRYU_TEKKO_P1,

    invaderXim.item.SUPERNAL_ABJURATION_LEGS,
    invaderXim.item.HEXED_HAKAMA,
    invaderXim.item.HEXED_HAKAMA_M1,
    invaderXim.item.TENRYU_HAKAMA,
    invaderXim.item.TENRYU_HAKAMA_P1,

    invaderXim.item.SUPERNAL_ABJURATION_FEET,
    invaderXim.item.HEXED_SUNE_ATE,
    invaderXim.item.HEXED_SUNE_ATE_M1,
    invaderXim.item.TENRYU_SUNE_ATE,
    invaderXim.item.TENRYU_SUNE_ATE_P1,

    invaderXim.item.TRANSITORY_ABJURATION_HEAD,
    invaderXim.item.HEXED_BONNET,
    invaderXim.item.HEXED_BONNET_M1,
    invaderXim.item.KHEPER_BONNET,
    invaderXim.item.KHEPRI_BONNET,

    invaderXim.item.TRANSITORY_ABJURATION_BODY,
    invaderXim.item.HEXED_JACKET,
    invaderXim.item.HEXED_JACKET_M1,
    invaderXim.item.KHEPER_JACKET,
    invaderXim.item.KHEPRI_JACKET,

    invaderXim.item.TRANSITORY_ABJURATION_HANDS,
    invaderXim.item.HEXED_WRISTBANDS,
    invaderXim.item.HEXED_WRISTBANDS_M1,
    invaderXim.item.KHEPER_WRISTBANDS,
    invaderXim.item.KHEPRI_WRISTBANDS,

    invaderXim.item.TRANSITORY_ABJURATION_LEGS,
    invaderXim.item.HEXED_KECKS,
    invaderXim.item.HEXED_KECKS_M1,
    invaderXim.item.KHEPER_KECKS,
    invaderXim.item.KHEPRI_KECKS,

    invaderXim.item.TRANSITORY_ABJURATION_FEET,
    invaderXim.item.HEXED_GAMASHES,
    invaderXim.item.HEXED_GAMASHES_M1,
    invaderXim.item.KHEPER_GAMASHES,
    invaderXim.item.KHEPRI_GAMASHES,

    -- Begin Escha - Ru'Aun Abjurations
    invaderXim.item.ABYSSAL_ABJURATION_HEAD,
    invaderXim.item.BEWITCHED_CROWN,
    invaderXim.item.VOODOO_CROWN,
    invaderXim.item.APOGEE_CROWN,
    invaderXim.item.APOGEE_CROWN_P1,

    invaderXim.item.ABYSSAL_ABJURATION_BODY,
    invaderXim.item.BEWITCHED_DALMATICA,
    invaderXim.item.VOODOO_DALMATICA,
    invaderXim.item.APOGEE_DALMATICA,
    invaderXim.item.APOGEE_DALMATICA_P1,

    invaderXim.item.ABYSSAL_ABJURATION_HANDS,
    invaderXim.item.BEWITCHED_MITTS,
    invaderXim.item.VOODOO_MITTS,
    invaderXim.item.APOGEE_MITTS,
    invaderXim.item.APOGEE_MITTS_P1,

    invaderXim.item.ABYSSAL_ABJURATION_LEGS,
    invaderXim.item.BEWITCHED_SLACKS,
    invaderXim.item.VOODOO_SLACKS,
    invaderXim.item.APOGEE_SLACKS,
    invaderXim.item.APOGEE_SLACKS_P1,

    invaderXim.item.ABYSSAL_ABJURATION_FEET,
    invaderXim.item.BEWITCHED_PUMPS,
    invaderXim.item.VOODOO_PUMPS,
    invaderXim.item.APOGEE_PUMPS,
    invaderXim.item.APOGEE_PUMPS_P1,

    invaderXim.item.AREAN_ABJURATION_HEAD,
    invaderXim.item.VEXED_SOMEN,
    invaderXim.item.JINXED_SOMEN,
    invaderXim.item.RYUO_SOMEN,
    invaderXim.item.RYUO_SOMEN_P1,

    invaderXim.item.AREAN_ABJURATION_BODY,
    invaderXim.item.VEXED_DOMARU,
    invaderXim.item.JINXED_DOMARU,
    invaderXim.item.RYUO_DOMARU,
    invaderXim.item.RYUO_DOMARU_P1,

    invaderXim.item.AREAN_ABJURATION_HANDS,
    invaderXim.item.VEXED_KOTE,
    invaderXim.item.JINXED_KOTE,
    invaderXim.item.RYUO_TEKKO,
    invaderXim.item.RYUO_TEKKO_P1,

    invaderXim.item.AREAN_ABJURATION_LEGS,
    invaderXim.item.VEXED_HAKAMA,
    invaderXim.item.JINXED_HAKAMA,
    invaderXim.item.RYUO_HAKAMA,
    invaderXim.item.RYUO_HAKAMA_P1,

    invaderXim.item.AREAN_ABJURATION_FEET,
    invaderXim.item.VEXED_SUNE_ATE,
    invaderXim.item.JINXED_SUNE_ATE,
    invaderXim.item.RYUO_SUNE_ATE,
    invaderXim.item.RYUO_SUNE_ATE_P1,

    invaderXim.item.BUSHIN_ABJURATION_HEAD,
    invaderXim.item.BEWITCHED_SCHALLER,
    invaderXim.item.VOODOO_SCHALLER,
    invaderXim.item.SOUVERAN_SCHALLER,
    invaderXim.item.SOUVERAN_SCHALLER_P1,

    invaderXim.item.BUSHIN_ABJURATION_BODY,
    invaderXim.item.BEWITCHED_CUIRASS,
    invaderXim.item.VOODOO_CUIRASS,
    invaderXim.item.SOUVERAN_CUIRASS,
    invaderXim.item.SOUVERAN_CUIRASS_P1,

    invaderXim.item.BUSHIN_ABJURATION_HANDS,
    invaderXim.item.BEWITCHED_HANDSCHUHS,
    invaderXim.item.VOODOO_HANDSCHUHS,
    invaderXim.item.SOUVERAN_HANDSCHUHS,
    invaderXim.item.SOUVERAN_HANDSCHUHS_P1,

    invaderXim.item.BUSHIN_ABJURATION_LEGS,
    invaderXim.item.BEWITCHED_DIECHLINGS,
    invaderXim.item.VOODOO_DIECHLINGS,
    invaderXim.item.SOUVERAN_DIECHLINGS,
    invaderXim.item.SOUVERAN_DIECHLINGS_P1,

    invaderXim.item.BUSHIN_ABJURATION_FEET,
    invaderXim.item.BEWITCHED_SCHUHS,
    invaderXim.item.VOODOO_SCHUHS,
    invaderXim.item.SOUVERAN_SCHUHS,
    invaderXim.item.SOUVERAN_SCHUHS_P1,

    invaderXim.item.CRONIAN_ABJURATION_HEAD,
    invaderXim.item.VEXED_CORONET,
    invaderXim.item.JINXED_CORONET,
    invaderXim.item.EMICHO_CORONET,
    invaderXim.item.EMICHO_CORONET_P1,

    invaderXim.item.CRONIAN_ABJURATION_BODY,
    invaderXim.item.VEXED_HAUBERT,
    invaderXim.item.JINXED_HAUBERT,
    invaderXim.item.EMICHO_HAUBERT,
    invaderXim.item.EMICHO_HAUBERT_P1,

    invaderXim.item.CRONIAN_ABJURATION_HANDS,
    invaderXim.item.VEXED_GAUNTLETS,
    invaderXim.item.JINXED_GAUNTLETS,
    invaderXim.item.EMICHO_GAUNTLETS,
    invaderXim.item.EMICHO_GAUNTLETS_P1,

    invaderXim.item.CRONIAN_ABJURATION_LEGS,
    invaderXim.item.VEXED_HOSE,
    invaderXim.item.JINXED_HOSE,
    invaderXim.item.EMICHO_HOSE,
    invaderXim.item.EMICHO_HOSE_P1,

    invaderXim.item.CRONIAN_ABJURATION_FEET,
    invaderXim.item.VEXED_GAMBIERAS,
    invaderXim.item.JINXED_GAMBIERAS,
    invaderXim.item.EMICHO_GAMBIERAS,
    invaderXim.item.EMICHO_GAMBIERAS_P1,

    invaderXim.item.CYLLENIAN_ABJURATION_HEAD,
    invaderXim.item.VEXED_MITRA,
    invaderXim.item.JINXED_MITRA,
    invaderXim.item.KAYKAUS_MITRA,
    invaderXim.item.KAYKAUS_MITRA_P1,

    invaderXim.item.CYLLENIAN_ABJURATION_BODY,
    invaderXim.item.VEXED_BLIAUT,
    invaderXim.item.JINXED_BLIAUT,
    invaderXim.item.KAYKAUS_BLIAUT,
    invaderXim.item.KAYKAUS_BLIAUT_P1,

    invaderXim.item.CYLLENIAN_ABJURATION_HANDS,
    invaderXim.item.VEXED_CUFFS,
    invaderXim.item.JINXED_CUFFS,
    invaderXim.item.KAYKAUS_CUFFS,
    invaderXim.item.KAYKAUS_CUFFS_P1,

    invaderXim.item.CYLLENIAN_ABJURATION_LEGS,
    invaderXim.item.VEXED_TIGHTS,
    invaderXim.item.JINXED_TIGHTS,
    invaderXim.item.KAYKAUS_TIGHTS,
    invaderXim.item.KAYKAUS_TIGHTS_P1,

    invaderXim.item.CYLLENIAN_ABJURATION_FEET,
    invaderXim.item.VEXED_BOOTS,
    invaderXim.item.JINXED_BOOTS,
    invaderXim.item.KAYKAUS_BOOTS,
    invaderXim.item.KAYKAUS_BOOTS_P1,

    invaderXim.item.GROVE_ABJURATION_HEAD,
    invaderXim.item.BEWITCHED_KABUTO,
    invaderXim.item.VOODOO_KABUTO,
    invaderXim.item.RAO_KABUTO,
    invaderXim.item.RAO_KABUTO_P1,

    invaderXim.item.GROVE_ABJURATION_BODY,
    invaderXim.item.BEWITCHED_TOGI,
    invaderXim.item.VOODOO_TOGI,
    invaderXim.item.RAO_TOGI,
    invaderXim.item.RAO_TOGI_P1,

    invaderXim.item.GROVE_ABJURATION_HANDS,
    invaderXim.item.BEWITCHED_KOTE,
    invaderXim.item.VOODOO_KOTE,
    invaderXim.item.RAO_KOTE,
    invaderXim.item.RAO_KOTE_P1,

    invaderXim.item.GROVE_ABJURATION_LEGS,
    invaderXim.item.BEWITCHED_HAIDATE,
    invaderXim.item.VOODOO_HAIDATE,
    invaderXim.item.RAO_HAIDATE,
    invaderXim.item.RAO_HAIDATE_P1,

    invaderXim.item.GROVE_ABJURATION_FEET,
    invaderXim.item.BEWITCHED_SUNE_ATE,
    invaderXim.item.VOODOO_SUNE_ATE,
    invaderXim.item.RAO_SUNE_ATE,
    invaderXim.item.RAO_SUNE_ATE_P1,

    invaderXim.item.JOVIAN_ABJURATION_HEAD,
    invaderXim.item.VEXED_BONNET,
    invaderXim.item.JINXED_BONNET,
    invaderXim.item.ADHEMAR_BONNET,
    invaderXim.item.ADHEMAR_BONNET_P1,

    invaderXim.item.JOVIAN_ABJURATION_BODY,
    invaderXim.item.VEXED_JACKET,
    invaderXim.item.JINXED_JACKET,
    invaderXim.item.ADHEMAR_JACKET,
    invaderXim.item.ADHEMAR_JACKET_P1,

    invaderXim.item.JOVIAN_ABJURATION_HANDS,
    invaderXim.item.VEXED_WRISTBANDS,
    invaderXim.item.JINXED_WRISTBANDS,
    invaderXim.item.ADHEMAR_WRISTBANDS,
    invaderXim.item.ADHEMAR_WRISTBANDS_P1,

    invaderXim.item.JOVIAN_ABJURATION_LEGS,
    invaderXim.item.VEXED_KECKS,
    invaderXim.item.JINXED_KECKS,
    invaderXim.item.ADHEMAR_KECKS,
    invaderXim.item.ADHEMAR_KECKS_P1,

    invaderXim.item.JOVIAN_ABJURATION_FEET,
    invaderXim.item.VEXED_GAMASHES,
    invaderXim.item.JINXED_GAMASHES,
    invaderXim.item.ADHEMAR_GAMASHES,
    invaderXim.item.ADHEMAR_GAMASHES_P1,

    invaderXim.item.SHINRYU_ABJURATION_HEAD,
    invaderXim.item.BEWITCHED_MASK,
    invaderXim.item.VOODOO_MASK,
    invaderXim.item.CARMINE_MASK,
    invaderXim.item.CARMINE_MASK_P1,

    invaderXim.item.SHINRYU_ABJURATION_BODY,
    invaderXim.item.BEWITCHED_MAIL,
    invaderXim.item.VOODOO_MAIL,
    invaderXim.item.CARMINE_SCALE_MAIL,
    invaderXim.item.CARMINE_SCALE_MAIL_P1,

    invaderXim.item.SHINRYU_ABJURATION_HANDS,
    invaderXim.item.BEWITCHED_FINGER_GAUNTLETS,
    invaderXim.item.VOODOO_FINGER_GAUNTLETS,
    invaderXim.item.CARMINE_FINGER_GAUNTLETS,
    invaderXim.item.CARMINE_FINGER_GAUNTLETS_P1,

    invaderXim.item.SHINRYU_ABJURATION_LEGS,
    invaderXim.item.BEWITCHED_CUISSES,
    invaderXim.item.VOODOO_CUISSES,
    invaderXim.item.CARMINE_CUISSES,
    invaderXim.item.CARMINE_CUISSES_P1,

    invaderXim.item.SHINRYU_ABJURATION_FEET,
    invaderXim.item.BEWITCHED_GREAVES,
    invaderXim.item.VOODOO_GREAVES,
    invaderXim.item.CARMINE_GREAVES,
    invaderXim.item.CARMINE_GREAVES_P1,

    invaderXim.item.TRITON_ABJURATION_HEAD,
    invaderXim.item.BEWITCHED_CAP,
    invaderXim.item.VOODOO_CAP,
    invaderXim.item.LUSTRATIO_CAP,
    invaderXim.item.LUSTRATIO_CAP_P1,

    invaderXim.item.TRITON_ABJURATION_BODY,
    invaderXim.item.BEWITCHED_HARNESS,
    invaderXim.item.VOODOO_HARNESS,
    invaderXim.item.LUSTRATIO_HARNESS,
    invaderXim.item.LUSTRATIO_HARNESS_P1,

    invaderXim.item.TRITON_ABJURATION_HANDS,
    invaderXim.item.BEWITCHED_GLOVES,
    invaderXim.item.VOODOO_GLOVES,
    invaderXim.item.LUSTRATIO_MITTENS,
    invaderXim.item.LUSTRATIO_MITTENS_P1,

    invaderXim.item.TRITON_ABJURATION_LEGS,
    invaderXim.item.BEWITCHED_SUBLIGAR,
    invaderXim.item.VOODOO_SUBLIGAR,
    invaderXim.item.LUSTRATIO_SUBLIGAR,
    invaderXim.item.LUSTRATIO_SUBLIGAR_P1,

    invaderXim.item.TRITON_ABJURATION_FEET,
    invaderXim.item.BEWITCHED_LEGGINGS,
    invaderXim.item.VOODOO_LEGGINGS,
    invaderXim.item.LUSTRATIO_LEGGINGS,
    invaderXim.item.LUSTRATIO_LEGGINGS_P1,

    invaderXim.item.VALE_ABJURATION_HEAD,
    invaderXim.item.BEWITCHED_CELATA,
    invaderXim.item.VOODOO_CELATA,
    invaderXim.item.ARGOSY_CELATA,
    invaderXim.item.ARGOSY_CELATA_P1,

    invaderXim.item.VALE_ABJURATION_BODY,
    invaderXim.item.BEWITCHED_HAUBERK,
    invaderXim.item.VOODOO_HAUBERK,
    invaderXim.item.ARGOSY_HAUBERK,
    invaderXim.item.ARGOSY_HAUBERK_P1,

    invaderXim.item.VALE_ABJURATION_HANDS,
    invaderXim.item.BEWITCHED_MUFFLERS,
    invaderXim.item.VOODOO_MUFFLERS,
    invaderXim.item.ARGOSY_MUFFLERS,
    invaderXim.item.ARGOSY_MUFFLERS_P1,

    invaderXim.item.VALE_ABJURATION_LEGS,
    invaderXim.item.BEWITCHED_BREECHES,
    invaderXim.item.VOODOO_BREECHES,
    invaderXim.item.ARGOSY_BREECHES,
    invaderXim.item.ARGOSY_BREECHES_P1,

    invaderXim.item.VALE_ABJURATION_FEET,
    invaderXim.item.BEWITCHED_SOLLERETS,
    invaderXim.item.VOODOO_SOLLERETS,
    invaderXim.item.ARGOSY_SOLLERETS,
    invaderXim.item.ARGOSY_SOLLERETS_P1,

    invaderXim.item.VENERIAN_ABJURATION_HEAD,
    invaderXim.item.VEXED_COIF,
    invaderXim.item.JINXED_COIF,
    invaderXim.item.AMALRIC_COIF,
    invaderXim.item.AMALRIC_COIF_P1,

    invaderXim.item.VENERIAN_ABJURATION_BODY,
    invaderXim.item.VEXED_DOUBLET,
    invaderXim.item.JINXED_DOUBLET,
    invaderXim.item.AMALRIC_DOUBLET,
    invaderXim.item.AMALRIC_DOUBLET_P1,

    invaderXim.item.VENERIAN_ABJURATION_HANDS,
    invaderXim.item.VEXED_GAGES,
    invaderXim.item.JINXED_GAGES,
    invaderXim.item.AMALRIC_GAGES,
    invaderXim.item.AMALRIC_GAGES_P1,

    invaderXim.item.VENERIAN_ABJURATION_LEGS,
    invaderXim.item.VEXED_SLOPS,
    invaderXim.item.JINXED_SLOPS,
    invaderXim.item.AMALRIC_SLOPS,
    invaderXim.item.AMALRIC_SLOPS_P1,

    invaderXim.item.VENERIAN_ABJURATION_FEET,
    invaderXim.item.VEXED_NAILS,
    invaderXim.item.JINXED_NAILS,
    invaderXim.item.AMALRIC_NAILS,
    invaderXim.item.AMALRIC_NAILS_P1,
}
